name: Build Docker Image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Building Docker Image
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          # 下方的name格式为：Docker Hub ID/自定义镜像名称
          name: sdgsdqwc/kxy
          username: 'sdgsdqwc'
          password: ')RN)UmfRw3U?BTL'
